name: Secret Scanner (Seguridad)

on:
  # Se ejecuta en cada push a la rama de desarrollo
  push:
    branches:
      - desarrollo

jobs:
  secrets_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Escáner de secretos
      - name: Scan Code for Secrets
        uses: 'gitleaks/gitleaks-action@v2'